init:
	terraform init

init-migrate-state:
	terraform init -migrate-state

reconfigure:
	terraform init -reconfigure

validate:
	terraform validate

format:
	terraform fmt

plan:
	terraform plan

apply:
	terraform apply

destroy:
	terraform destroy
