- hosts: all
  become: true
  vars_files:
    - vault.yml

  tasks:
    - name: Настроить sudo без пароля
      copy:
        dest: /etc/sudoers.d/ubuntu
        content: "ubuntu ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        mode: "0440"

    - name: Update Ghost configuration
      template:
        src: env.j2
        dest: .env
        mode: "644"
    - name: install ghost
      community.docker.docker_container:
        name: ghost
        image: ghost:5.79.3
        ports:
          - "{{ GHOST_PORT }}:2368"
        env_file: .env

  roles:
    - role: datadog.datadog
